version: "3.8"
services:
  # gluetun:
  #   image: qmcgaw/gluetun
  #   container_name: gluetun
  #   cap_add:
  #    - NET_ADMIN
  #   devices:
  #    - /dev/net/tun:/dev/net/tun
  #   # environment:  # Pakai ini kalo punya wireguard sendiri
  #   #  - VPN_SERVICE_PROVIDER=custom
  #   #  - VPN_TYPE=wireguard
  #   #  - WIREGUARD_PRIVATE_KEY=PRIVATE_KEY
  #   #  - WIREGUARD_ADDRESSES=172.16.0.2/32
  #   #  - WIREGUARD_PUBLIC_KEY=PUBLIC_KEY
  #   #  - WIREGUARD_ENDPOINT_IP=162.159.192.1
  #   #  - WIREGUARD_ENDPOINT_PORT=2408
  #   #  - TZ=Asia/Jakarta
  #   #  - UPDATER_PERIOD=24h
  #   environment:
  #    - VPN_SERVICE_PROVIDER=nordvpn
  #    - VPN_TYPE=wireguard
  #    - WIREGUARD_PRIVATE_KEY=PRIVATE_KEY
  #    - SERVER_HOSTNAMES=sg545.nordvpn.com
  #    - TZ=Asia/Jakarta
  #    - UPDATER_PERIOD=24h
  #   ports:
  #    - "80:80"
  #    - "8080:8080"
  #   restart: on-failure
  app:
    build: .
    # network_mode: "service:gluetun" # komen aja kalo ma matiin vpn nya
    command: bash start.sh
    restart: on-failure
    # Removed ports section